version: "3.9"

services:
  frontend:
    build:
      context: ./shop/
      args:
        HOST_API: ${SERVER_API}
    ports:
    - "${PORT_SHOP}:3001"

  backoffice:
    build:
      context: ./admin/
      args:
        HOST_API: ${SERVER_API}
    ports:
      - "${PORT_ADMIN}:3002"