export const ROUTES = {
  HOME: "/",
  CHECKOUT: "/checkout",
  PROFILE: "/profile",
  CHANGE_PASSWORD: "/change-password",
  ABOUT: "/about",
  ORDERS: "/orders",
  HELP: "/help",
  LOGOUT: "/logout",
  OFFERS: "/offers",
  ORDER_RECEIVED: "/order-received",
  PRODUCT: "/products",
  ORDER: "/order",
  PRIVACY: "/privacy",
  TERMS: "/terms",
  CONTACT: "/contact",
};
