export const ROUTES = {
  DASHBOARD: "/dashboard",
  LOGIN: "/",
  ORDER_STATUS: "/order-status",
  ORDERS: "/orders",
  PRODUCTS: "/products",
  COUPONS: "/coupons",
  CUSTOMERS: "/customers",
  TAXES: "/taxes",
  INVOICES: "/invoices",
  SHIPPINGS: "/shippings",
  SHIPPINGS_AREA: "/shippings-area",
  SETTINGS: "/settings",
  CATEGORIES: "/categories",
  CATEGORIES_POSITION: "/categories/position",
  WEEKLY_MENU: '/weekly-menu',
  BANNERS: "/banners",
  FAQS: "/faqs",
  COURIERS: "/couriers",
  TYPES: "/types",
  PROFILE_UPDATE: "/profile-update",
  LOGOUT: "/logout",
  ATTRIBUTES: "/attributes",
  ATTRIBUTE_VALUES: "/attribute-values",
};
